# Tarea 01 — Python y NumPy

**Instrucciones:** Completa cada celda de código con tu respuesta. No modifiques las celdas de texto.  
Cada pregunta indica exactamente qué debes escribir.

---
## Parte 1 — Python básico

**P1.** Crea una variable llamada `nombre` con tu nombre, y otra llamada `edad` con tu edad.  
Luego imprime el mensaje: `Hola, me llamo Ana y tengo 22 años.` (con tus datos).

In [22]:
# Tu respuesta aquí
nombre = 'Jimena'
Edad = 23

print("Hola, mi nombre es", nombre, "y tengo", Edad, "años.")


Hola, mi nombre es Jimena y tengo 23 años.


**P2.** Dada la lista `numeros = [10, 25, 3, 47, 8, 15]`:  
- Imprime el primer y el último elemento.  
- Imprime los tres primeros elementos usando slicing.  
- Agrega el número `99` al final de la lista.

In [23]:
numeros = [10, 25, 3, 47, 8, 15]

# Tu respuesta aquí

# Imprime el primer y el último número de la lista
primer_numero = numeros[0]
ultimo_numero = numeros[-1]
print("El primer número es:", primer_numero)
print("El último número es:", ultimo_numero)

#Imprimir los 3 primeros números de la lista utilizando slicing
print(numeros[:3])

# Agrega el número 99 al final de la lista y luego imprímela
numeros.insert(6, 99)
print(numeros)




El primer número es: 10
El último número es: 15
[10, 25, 3]
[10, 25, 3, 47, 8, 15, 99]


**P3.** Dado el diccionario `estudiante` con las llaves `nombre`, `carrera` y `promedio`,  
escribe un `if` que imprima `"Aprobado"` si el promedio es mayor o igual a 6, y `"Reprobado"` si no.

In [24]:
estudiante = {"nombre": "Carlos", "carrera": "Sistemas", "promedio": 7.5}

if estudiante["promedio"] >= 6:
    print("Aprobado")
else:
    print("Reprobado")



Aprobado


**P4.** Crea una función llamada `calcular_area` que reciba `base` y `altura` y devuelva el área de un triángulo (`base * altura / 2`).  
Llama la función con `base=5` y `altura=8` e imprime el resultado.

In [25]:
# Tu respuesta aquí

base = 5
altura = 8

calcular_area = (base * altura) / 2
print("El área del triángulo es:", calcular_area)

El área del triángulo es: 20.0


**P5.** Usa una **list comprehension** para crear una lista con los cuadrados de los números del 1 al 10.  
Imprime la lista resultante.

In [26]:
# Tu respuesta aquí
j = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

out = [x**2 for x in j]
print(out)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


---
## Parte 2 — NumPy

In [27]:
import numpy as np

**P6.** Crea los siguientes arreglos e imprime su `shape` y `dtype`:  
- Un arreglo con los valores `[1.5, 2.5, 3.5, 4.5]`  
- Una matriz de ceros de 3 filas × 4 columnas  
- Un arreglo con 6 valores igualmente espaciados entre 0 y 1 (usando `linspace`)

In [32]:
# Tu respuesta aquí

# 1. Arreglo con valores específicos
a = np.array([1.5, 2.5, 3.5, 4.5])

# 2. Matriz de ceros de 3 filas x 4 columnas
b = np.zeros((3, 4))

# 3. Arreglo con 6 valores igualmente espaciados entre 0 y 1
c = np.linspace(0, 1, 6)

# Impresión de resultados
print(f"Arreglo A: {a}")
print(f"Shape: {a.shape}, Dtype: {a.dtype}")
print("-" * 30)

print(f"Arreglo B (Ceros):\n{b}")
print(f"Shape: {b.shape}, Dtype: {b.dtype}")
print("-" * 30)

print(f"Arreglo C (Linspace): {c}")
print(f"Shape: {c.shape}, Dtype: {c.dtype}")

Arreglo A: [1.5 2.5 3.5 4.5]
Shape: (4,), Dtype: float64
------------------------------
Arreglo B (Ceros):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape: (3, 4), Dtype: float64
------------------------------
Arreglo C (Linspace): [0.  0.2 0.4 0.6 0.8 1. ]
Shape: (6,), Dtype: float64


**P7.** Dado el arreglo `a = np.arange(1, 13)`, usa `reshape` para convertirlo en una matriz de 3 × 4.  
Luego imprime el valor máximo, el valor mínimo y la posición (índice) del máximo.

In [37]:
a = np.arange(1, 13)

# Tu respuesta aquí

# 1. Crear el arreglo del 1 al 12
a = np.arange(1, 13)

# 2. Convertirlo en una matriz de 3 filas x 4 columnas
matriz = a.reshape(3, 4)

# 3. Obtener estadísticas
maximo = matriz.max()
minimo = matriz.min()
posicion_maximo = matriz.argmax()

# Impresión de resultados
print("Matriz resultante (3x4):")
print(matriz)
print(f"\nValor máximo: {maximo}")
print(f"Valor mínimo: {minimo}")
print(f"Posición ndice valor máximo: {posicion_maximo}")

Matriz resultante (3x4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Valor máximo: 12
Valor mínimo: 1
Posición ndice valor máximo: 11


**P8.** Crea dos arreglos de 5 elementos con `np.random.randint` (valores entre 1 y 20).  
Súmalos, réstalos y multiplícalos elemento por elemento. Imprime cada resultado.

In [38]:
# Tu respuesta aquí

# 1. Crear dos arreglos de 5 elementos con valores entre 1 y 20
# Nota: el límite superior en randint es exclusivo, por eso usamos 21
a = np.random.randint(1, 21, size=5)
b = np.random.randint(1, 21, size=5)

# 2. Realizar las operaciones
suma = a + b
resta = a - b
multiplicacion = a * b

# 3. Imprimir los resultados
print(f"Arreglo A: {a}")
print(f"Arreglo B: {b}")
print("-" * 30)
print(f"Suma:           {suma}")
print(f"Resta:          {resta}")
print(f"Multiplicación: {multiplicacion}")


Arreglo A: [17  4 10 19 12]
Arreglo B: [10 20 10 17  3]
------------------------------
Suma:           [27 24 20 36 15]
Resta:          [  7 -16   0   2   9]
Multiplicación: [170  80 100 323  36]


**P9.** Dado el arreglo `notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1])`,  
usa **indexación booleana** para obtener solo las notas mayores o iguales a 6. Imprime el resultado.

In [39]:
notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1])

# Tu respuesta aquí

# 1. Crear el arreglo de notas
notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1])

# 2. Aplicar indexación booleana
# notas >= 6 crea una "máscara" de valores True/False
notas_aprobadas = notas[notas >= 6]

# 3. Imprimir el resultado
print(f"Todas las notas: {notas}")
print(f"Notas mayores o iguales a 6: {notas_aprobadas}")

Todas las notas: [ 8.5  6.   9.2  4.3  7.8  5.5 10.   3.1]
Notas mayores o iguales a 6: [ 8.5  6.   9.2  7.8 10. ]
